server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Tasks
          uri: http://localhost:8081/
          predicates:
            - Path=/tasks/**
        - id: Books
          uri: http://localhost:8082/
          predicates:
            - Path=/books/**